directory:
  project: '/Users/leosword/Documents/MarmoSync/demos/double_40s_1stick'
  model: ['/Users/leosword/Documents/MarmoSync/data/models/centroid_v1.9', 
          '/Users/leosword/Documents/MarmoSync/data/models/id_centered_instance_v2.4']
  vae: '/Users/leosword/Documents/MarmoSync/data/models/VAE_v1.h5'
  

animal:
  number: 2
  bodyparts: ['head', 'leftear', 'rightear', 'neck', 
              'leftelbow', 'rightelbow', 'lefthand', 'righthand', 
              'spinemid', 'tailbase', 'leftknee', 'rightknee', 
              'leftfoot', 'rightfoot', 'tailmid', 'tailend']


calibration:
  board_size: [11, 8]
  board_square_side_length: 45 # mm
  fisheye: true


visualization:
  skeleton:
    - ['head', 'leftear', 'neck', 'rightear', 'head']
    - ['tailbase', 'tailmid', 'tailend']
    - ['neck', 'spinemid', 'tailbase']
    - ['lefthand', 'leftelbow', 'neck', 'rightelbow', 'righthand']
    - ['leftfoot', 'leftknee', 'tailbase', 'rightknee', 'rightfoot']


filter:
  threshold: 0.2
  

triangulation:
  user_define_axes: true


optimization:
  enable: true
  n_deriv_smooth: 1
  scale_smooth: 2
  scale_length: 0
  scale_length_weak: 0

  bodypart_distance:
    'head - rightear': 21.0 # mm
    'head - leftear': 21.0
    'rightear - neck': 52.0
    'leftear - neck': 52.0
    'neck - spinemid': 58.0
    'spinemid - tailbase': 73.0
    'neck - rightelbow': 73.0
    'rightelbow - righthand': 54.0
    'neck - leftelbow': 73.0
    'leftelbow - lefthand': 54.0
    'tailbase - rightknee': 90.0
    'tailbase - leftknee': 90.0

  bodypart_distance_weak:
    'tailbase - tailmid': 103.0
    'tailmid - tailend': 103.0
    'rightknee - rightfoot': 42.0
    'leftknee - leftfoot': 42.0