directory:
  project: '/Users/leosword/Documents/MarmoSync/demos/single_30s_test'
  model: '/Users/leosword/Documents/MarmoSync/data/models/single_v1.2'


animal:
  number: 1
  bodyparts: ['head', 'leftear', 'rightear', 'neck', 
              'leftelbow', 'rightelbow', 'lefthand', 'righthand', 
              'spinemid', 'tailbase', 'leftknee', 'rightknee', 
              'leftfoot', 'rightfoot', 'tailmid', 'tailend']


calibration:
  board_size: [11, 8]
  board_square_side_length: 45 # mm
  fisheye: true


visualization:
  skeleton:
    - ['head', 'leftear', 'neck', 'rightear', 'head']
    - ['neck', 'spinemid', 'tailbase']
    - ['leftfoot', 'leftknee', 'tailbase', 'rightknee', 'rightfoot']
    - ['lefthand', 'leftelbow', 'neck', 'rightelbow', 'righthand']
    - ['tailbase', 'tailmid', 'tailend']


filter:
  threshold: 0.2
  

triangulation:
  user_define_axes: true


optimization:
  enable: true
  n_deriv_smooth: 1
  scale_smooth: 1
  scale_length: 2
  scale_length_weak: 1

  bodypart_distance:
    'head - rightear': 30.0 # mm
    'head - leftear': 30.0
    'rightear - neck': 40.0
    'leftear - neck': 40.0
    'neck - spinemid': 80.0
    'spinemid - tailbase': 80.0
    'neck - rightelbow': 70.0
    'rightelbow - righthand': 70.0
    'neck - leftelbow': 70.0
    'leftelbow - lefthand': 70.0
    'tailbase - rightknee': 70.0
    'tailbase - leftknee': 70.0

  bodypart_distance_weak:
    'tailbase - tailmid': 140.0
    'tailmid - tailend': 140.0
    'rightknee - rightfoot': 80.0
    'leftknee - leftfoot': 80.0